name: Build Android Kernel

on:
  # Allows manual triggering of the workflow
  workflow_dispatch:
    inputs:
      kernel_suffix:
        description: 'Custom Kernel Suffix (e.g., -MyKernel-v1)'
        required: false
        default: '-android14-TG@qdykernel'
  # Triggers on pushes to the main branch
  push:
    branches:
      - main

jobs:
  build_kernel:
    name: Build for ${{ matrix.device.name }}
    runs-on: ubuntu-22.04
    strategy:
      # Defines a build matrix to run jobs for multiple devices
      matrix:
        device:
          - name: "oneplus_ace5"
            manifest: "oneplus_ace5.xml"
          - name: "oneplus_12"
            manifest: "oneplus12_v.xml"
          - name: "oneplus_pad_pro"
            manifest: "oneplus_pad_pro_v.xml"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev \
            lib32z1-dev libelf-dev liblz4-tool libncurses5-dev libssl-dev \
            libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev python3

      - name: Install Google Repo Tool
        run: |
          mkdir -p ~/.local/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.local/bin/repo
          chmod a+x ~/.local/bin/repo
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run Build Script
        env:
          # Pass matrix variables and workflow inputs to the build script
          DEVICE_NAME: ${{ matrix.device.name }}
          REPO_MANIFEST: ${{ matrix.device.manifest }}
          KERNEL_SUFFIX: ${{ github.event.inputs.kernel_suffix }}
          ENABLE_KPM: true
          ENABLE_LZ4KD: true
        run: |
          chmod +x ./build_kernel.sh
          ./build_kernel.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Build-${{ matrix.device.name }}
          path: ${{ github.workspace }}/output/

