name: Kernel Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git curl ccache flex bison libssl-dev libelf-dev bc zip

      - name: Make ace5.sh executable
        run: chmod +x ace5.sh

      - name: Run ace5.sh non-interactively
        env:
          # Set default values for interactive prompts
          DEVICE_CHOICE: 1
          KERNEL_SUFFIX: "-android14-TG@qdykernel"
          ENABLE_KPM: "y"
          ENABLE_LZ4KD: "y"
        run: |
          # Provide input to the script for all prompts
          # 1: OnePlus Ace 5, default suffix, enable kpm, enable lz4+zstd
          printf "%s\n%s\n%s\n%s\n" "$DEVICE_CHOICE" "$KERNEL_SUFFIX" "$ENABLE_KPM" "$ENABLE_LZ4KD" | ./ace5.sh

      - name: Upload built kernel package
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: kernel-package
          path: |
            $HOME/kernel_oneplus_ace5/AnyKernel3/*.zip
            $HOME/kernel_oneplus_ace5/AnyKernel3/Image
